server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    #
    #url: jdbc:mariadb://localhost:3306/whereecojpa?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    url: jdbc:mariadb://whereechodb-maria.c9meh9rc5ju2.ap-northeast-2.rds.amazonaws.com:3306/whereeco?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: ${datasourceusername} #
    password: ${password} # rds 환경에 맞게 변경#
    #driver-class-name: org.mariadb.jdbc.Driver  # rds 환경에서 사용하지 않음


  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql : true # sql 출력 보기 편하게
        default_batch_fetch_size: 1000

    show-sql: true  # sql 출력
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace